"""Add job description and ats details to resume

Revision ID: 39506cc49b30
Revises: 53f5b866064c
Create Date: 2026-07-08 22:34:59.072870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39506cc49b30'
down_revision: Union[str, Sequence[str], None] = '53f5b866064c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('job_description', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('ats_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'ats_details')
    op.drop_column('resumes', 'job_description')
    # ### end Alembic commands ###
